/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.otus;

import com.google.common.base.Strings;
import java.util.logging.Level;
import java.util.logging.Logger;

@SuppressWarnings("java:S106")
public class HelloOtus {
    private static final Logger logger = Logger.getLogger(HelloOtus.class.getName());

    public static void main(String[] args) {
        logger.info("Hello from Otus!");
        HelloOtus hello = new HelloOtus();
        hello.testGuava();
    }

    public void testGuava() {
        String testStr = "";
        boolean isEmpty = Strings.isNullOrEmpty(testStr);

        if (logger.isLoggable(Level.INFO)) {
            logger.info(String.format("Is string empty or null? %s", isEmpty));
        }
    }
}
